### ISSUE TITLE
Demo link points to unrelated project

### ISSUE THREAD

**Issue by cadars** [sibiraj-s/svelte-tiptap#1]
https://stackblitz.com/edit/svelte-tiptap

**Comment by sibiraj-s** [comment]
Oh. That. Yeah I was trying to create a demo with svelte in stackblitz and it didn't quite endup well. I will fix it soon. Just for now, you can checkout [contributing.md](https://github.com/sibiraj-s/svelte-tiptap/blob/master/.github/CONTRIBUTING.md) and fire up the local server.

**Comment by sibiraj-s** [comment]
Updated the readme. Added a repl https://svelte.dev/repl/5e09f7b8b0ae421081107a404bb7c280?version=3.42.1
