### ISSUE TITLE
Minimal example in readme does not work without one extension

### ISSUE THREAD

**Issue by carstenjaksch** [sibiraj-s/svelte-tiptap#12]
Hi,

I use SvelteKit and need to add a minimum of one extension in order for it to load. The readme example does not include any extensions.

Until that, I got the error `Uncaught (in promise) RangeError: Schema is missing its top node type ('doc')`.

My working code:

```svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import type { Readable } from 'svelte/store';
	import { createEditor, EditorContent } from 'svelte-tiptap';
	import StarterKit from '@tiptap/starter-kit';

	let editor: Readable<Editor>;

	onMount(() => {
		editor = createEditor({
			extensions: [StarterKit], // added one extension
			content: `Hello world!`
		});
	});
</script>

<EditorContent editor={$editor} />
```

**Comment by carstenjaksch** [comment]
I forgot to mention a TypeScrpt error. Adding `import type { Editor } from 'svelte-tiptap';` fixed the issue.

<img width="458" alt="Bildschirmfoto 2022-09-10 um 20 49 48" src="https://user-images.githubusercontent.com/82714642/189497603-11edb2bc-1da2-4fb1-98a6-b159db6b241b.png">

**Comment by sibiraj-s** [comment]
Updated README. Thanks 👍
