### ISSUE TITLE
Packaging Upgrades

### ISSUE THREAD

**Issue by DougAnderson444** [sibiraj-s/svelte-tiptap#16]
Hey this is a really cool TipTap extension, I'm a big fan of Svelte and noticed most of their TipTap stuff is React & Vue.

I have noticed that the current build of this repo doesn't add `.js` extensions when the TS is transformed, which is messing up some of my use of this package. 

Do you mind if I submit a Pull Request to updated the packaging pipeline to fix this? I've already made the changes in my fork.

**Comment by DougAnderson444** [comment]
@sibiraj-s The original package error I was seeing:

![image](https://user-images.githubusercontent.com/6699901/225083624-641602f4-4acd-4c52-ac5b-32fa26a7af90.png)

It is because unpkg doesn't like Typescript file, specifically their lack of extensions. But the new packaging method adds the extensions when transforming them to javascript.

**Comment by sibiraj-s** [comment]
A lot has been updated with v1.0.0, may be it shouldn't throw any errors. 

Thank you
