### ISSUE TITLE
Typescript types are not in the dist

### ISSUE THREAD

**Issue by chanced** [sibiraj-s/svelte-tiptap#2]
All that is being generated is index.js and index.js.map.

**Comment by chanced** [comment]
Would you consider migrating the package to kit? I can get the types generating out package asis, using rollup but svekit package generates types for components as well.

**Comment by sibiraj-s** [comment]
I haven't used sveltekit yet. and not sure if it is capable of building libraries.

**Comment by chanced** [comment]
It is. https://kit.svelte.dev/docs#packaging

**Comment by sibiraj-s** [comment]
Awesome. I can give it a go today.

**Comment by sibiraj-s** [comment]
Let me know if you can to take this up.

**Comment by sibiraj-s** [comment]
Migrated to svelte-kit. Published in v0.4.0
