### ISSUE TITLE
Whole node is draggable

### ISSUE THREAD

**Issue by chrisjowen** [sibiraj-s/svelte-tiptap#31]
Hi, 

Appologies if this is more of a tiptap core question, but your docs state:

```
Dragging
To make your node views draggable, set draggable: true in the extension and add data-drag-handle to the DOM element that should function as the drag handle.
```

When I add draggable: true then the whole node is draggable, but this implies that I can add  data-drag-handle to s single node and have this only draggable but that doesn't seem to function as expected. 

Any Ideas?

Chris

**Comment by sibiraj-s** [comment]
> but this implies that I can add data-drag-handle to s single node and have this only draggable but that doesn't seem to function as expected

Can you clarify this?

And how draggable nows work is that.

When you add draggable to a node, the node becomes ready to be dragged, but can't be dragged yet, unless TipTap finds a drag handle and now you should add `data-drag-handle` to the element of the node, which should act as a drag handle. It can be an entire node or just a block in the node, thats upto you.

**Comment by chrisjowen** [comment]
Sure so lets take this simple component:


`
<NodeViewWrapper
  class={cx("svelte-component", { selected })}
  action={draggable}
>
<div class="bg-black text-white mb-4">
  DONT DRAG ME
</div>
<div class="bg-red-400 " data-drag-handle>
  DRAG ME
</div>
</NodeViewWrapper> 
`

What I was expecting here is that if I attempt to drag on the "DONT DRAG ME" div it wont, but the "DRAG ME" will. I was also expecting that the ghosted drag element would only be the "  DRAG ME" div. 

Right now I can drage anywhere and it drags the whole thing

Additional ts code:

`import { Node, mergeAttributes } from '@tiptap/core';
import { SvelteNodeViewRenderer } from 'svelte-tiptap';
import MessageExtension from './MessageExtension.svelte';


export const SvelteMessageExtension =  Node.create({
  name: 'svelte-message-component',
  group: 'block',
  atom: true,
  draggable: true, // Optional: to make the node draggable
  inline: false,
  
  addAttributes() {
    return {
      id: {
        default: 1,
      },
    };
  },

  parseHTML() {
    return [{ tag: 'svelte-message-component' }];
  },

  renderHTML(all) {
    let { HTMLAttributes } = all;
    return ['svelte-message-component', mergeAttributes(HTMLAttributes)];
  },

  addNodeView() {
    return SvelteNodeViewRenderer(MessageExtension);
  },
});`

**Comment by chrisjowen** [comment]
<img width="1728" alt="image" src="https://github.com/sibiraj-s/svelte-tiptap/assets/80583/479f1c27-81d6-4aae-a812-2f224254f34e">

**Comment by sibiraj-s** [comment]
Oh.

The `data-drag-handle` is just to tell tiptap which should act as handle to drag the node. So once you add to an element inside the node, the element will act as handle for the whole node.

The element alone is not draggable outside a node or within the node.

Did I understood and answer the question as expected?

**Comment by sibiraj-s** [comment]
Closing this as it appears to be not an issue and works as expected. Also the question is answered. For further questions, feel free to create a discussion thread.

Thanks.
