### ISSUE TITLE
What is the purpose of svelte-component-selected?

### ISSUE THREAD

**Issue by einarpersson** [sibiraj-s/svelte-tiptap#39]
Hi! In the README there is
```
class={cx('svelte-component', { selected })}
```

What is the purpose of this? Is it mandatory and tied to some tiptap-functionality (events etc), or is it just something for styling in this example? (if so, perhaps remove it so that it does not confuses)

**Comment by sibiraj-s** [comment]
No classes passed through component is tied to any functionality. It was just initially added as a showcase some of available incoming props. 

It can be updated/removed I guess.

**Comment by sibiraj-s** [comment]
Updated the README, hope its clear now.
