### ISSUE TITLE
Remove default styles

### ISSUE THREAD

**Issue by iPaulPro** [sibiraj-s/svelte-tiptap#45]
Tiptap is a headless solution, but this library injects `.ProseMirror` styles. Can this be disabled? I'd argue that it should be opt-in, not on by default.

**Comment by iPaulPro** [comment]
Or perhaps I a misunderstanding? I see `.ProseMirror` and when the field is focued, `.ProseMirror-focued`. Are those part of  tiptap, or added by this library? Apologies if not!

**Comment by iPaulPro** [comment]
[Found it](https://github.com/ueberdosis/tiptap/blob/4474d056daf9280ebb10b31f98bb000e953132e5/packages/core/src/style.ts#L69). So much for "headless", huh. 😅

**Comment by sibiraj-s** [comment]
Ha. Glad you figured it. 😄

Yeah. Some are added by tiptap, and some by Prosemirror itself. Not sure about the styles injected by tiptap, but the styles injected by Prosemirror is required for the editor to function as expected.
