### ISSUE TITLE
Error when evaluating SSR module

### ISSUE THREAD

**Issue by TBenTiCon** [sibiraj-s/svelte-tiptap#59]
Hi, im getting this Error when importing the package:
```js
Error when evaluating SSR module /src/lib/blocks/rich-text/index.ts: failed to import "@tiptap/extension-bubble-menu" |- Error: Cannot find module '@tiptap/extension-bubble-menu' imported from ...
```

The tiptap extension is installed and can be used. Does this have something todo with sveltekit?

**Comment by sibiraj-s** [comment]
Could be, I don't see anything relevant to this package. Try clearing your build cache once. or may be even delete and reinstall node_modules.

**Comment by sibiraj-s** [comment]
Closing this since this appears not be an issue with this package.

**Comment by TBenTiCon** [comment]
Just had time to try out clientside rendering, and that seems to solve the issue!
