### ISSUE TITLE
tiptap, prosemirror error

### ISSUE THREAD

**Issue by mzehrer** [sibiraj-s/svelte-tiptap#63]
I get the following error when loading the editor:

![image](https://github.com/user-attachments/assets/3742f0a3-6599-4f90-8235-8b714309eae1)

Code is:

```
<script>
    import { onMount } from "svelte";
    import { createEditor, Editor, EditorContent } from "svelte-tiptap";
    import StarterKit from "@tiptap/starter-kit";

    let editor = $state();

    onMount(() => {
      editor = createEditor({
           extensions: [StarterKit],
           content: `
             <p>This is still the text editor you're used to, but enriched with node views.</p>
             <svelte-counter-component count="0"></svelte-counter-component>
             <p>This is an editable component</p>
             <svelte-editable-component>This is editable</svelte-editable-component>
             <p>Did you see that? That's a Svelte component. We are really living in the future.</p>
           `,
           editorProps: {
             attributes: {
               class: 'border-2 border-black rounded-b-md p-3 outline-none',
             },
           },
         });
    });
</script>

<EditorContent editor={$editor} />
```

**Comment by sibiraj-s** [comment]
Similar issues happens when prosemirror is updated, the only solution worked so far is to uninstall and re-install the package or deleting lock file and node modules together and doing npm install or yarn ... etc.

can you try that once?

**Comment by mzehrer** [comment]
Tried, but it didn't make any difference.

**Comment by sibiraj-s** [comment]
Could you give me some more information? I'll see if I could find anything may be a reproducible setup, can't figureout anything from the screenshot and code?

Also, the same setup I have in https://github.com/sibiraj-s/svelte-tiptap/blob/master/src/routes/%2Bpage.svelte and is working fine

You could run that in your local, the dev setup is straightforward, just 

```bash
## clone and cd into repo and then
npm install
npm run dev
```

TBH, this is definitely not an issue from this library(mostly), Only two(bubble and floating menu plugin) plugins are exported  and those are not used by default, you have to import and use them manually and you seem to be not using any of those.
