### ISSUE TITLE
Demo site and basic tutorial don't work

### ISSUE THREAD

**Issue by uxer** [sibiraj-s/svelte-tiptap#8]
Nothing that could help me test this works. I don't think this needs further elaboration.

**Comment by sibiraj-s** [comment]
Can you check the examples here https://sibiraj-s.github.io/svelte-tiptap/. Source can be found here. https://github.com/sibiraj-s/svelte-tiptap/tree/master/src/routes.

Repl was created a long time back. could have been broken by some release, will check that.

**Comment by sibiraj-s** [comment]
Fixed https://svelte.dev/repl/fa178c3b141a4c52a2d74eecb2279c4b
