### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'element')     at init

### ISSUE THREAD

**Issue by joshuavachon25** [sibiraj-s/svelte-tiptap#9]
I get this error when trying to implement the plugin in my Sveltekit Project (Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'element') at init_).

The code comes from the readme with a few exceptions, because I don't use Typescript:
``` Svelte
<script >
    import { onMount, onDestroy } from 'svelte';
    import { createEditor, EditorContent } from 'svelte-tiptap';
    import StarterKit from "@tiptap/starter-kit";

    let editor

    onMount(() => {
        editor = createEditor({
            extensions: [
                StarterKit,
        ],
            content: `Hello world!`,
        });
    });
</script>

<EditorContent editor={editor} />
```

**Comment by ranjanified** [comment]
> I get this error when trying to implement the plugin in my Sveltekit Project (Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'element') at init_).
> 
> The code comes from the readme with a few exceptions, because I don't use Typescript:
> 
> ```svelte
> <script >
>     import { onMount, onDestroy } from 'svelte';
>     import { createEditor, EditorContent } from 'svelte-tiptap';
>     import StarterKit from "@tiptap/starter-kit";
> 
>     let editor
> 
>     onMount(() => {
>         editor = createEditor({
>             extensions: [
>                 StarterKit,
>         ],
>             content: `Hello world!`,
>         });
>     });
> </script>
> 
> <EditorContent editor={editor} />
> ```

@joshuavachon25 ...  Does this help?
```ts
<EditorContent editor={$editor} />
```

**Comment by sibiraj-s** [comment]
Thanks @ranjanified
